### ISSUE TITLE
why use requestAnimationFrame in withScroll component

### ISSUE THREAD

**Issue by barroudjo** [Stanko/react-window-decorators#1]
Just a technical question, but I don't get why you call ``requestAnimationFrame`` in the higher order component, given that it is already used in the scrollManager ?
Thanks for this well optimized library !

(here is the line I'm referring to)
https://github.com/Stanko/react-window-decorators/blob/6f7509eec8a861ceccae26156230705577d6a5d5/src/scroll.js#L48

**Comment by Stanko** [comment]
Hello and sorry, I never got a notification for this issue. 

They say it is better late than never 🙈 

Well, my idea is this - custom scroll event will be triggered in it's own `requestAnimationFrame` but whatever components uses it, will add more repaint logic, which won't fit in the same `requestAnimationFrame`. That's why I think that logic should be wrapped in additional `requestAnimationFrame` call, to prevent forced repaints.

I might be wrong, and it would be nice to see deeper performance tests.

Cheers!
